CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    login TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    age INTEGER NOT NULL,
    balance DOUBLE PRECISION NOT NULL,
    credit_limit DOUBLE PRECISION NOT NULL,
    role TEXT NOT NULL
);